# Generated by Django 3.2 on 2022-05-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_coupon_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='price_boundary',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
