# Generated by Django 3.2 on 2022-05-18 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0005_alter_coupon_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='is_active',
        ),
    ]
