# Generated by Django 3.2 on 2022-05-23 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0008_coupon_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='user',
        ),
    ]
