# Generated by Django 3.2 on 2022-05-24 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0010_couponuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(choices=[('PBO', 'Product Based'), ('CBO', 'Category Based'), ('FLO', 'Flat'), ('PVO', 'Percentage Based'), ('MOV', 'Minimum Order Value'), ('LCO', 'Limited Coupon')], default='PVO', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='percentage',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='price_boundary',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
