# Generated by Django 3.2 on 2022-05-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0011_auto_20220524_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='max_discount_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
