# Generated by Django 3.2 on 2022-05-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0012_alter_coupon_max_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='category_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
