# Generated by Django 3.2 on 2022-05-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0013_auto_20220524_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='price_boundary',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
