# Generated by Django 3.2 on 2022-05-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20220505_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jti',
            field=models.CharField(default='197361b146c7bd7d05ff52a30455277992a21e686785f49ec04b92fcbc78e691', editable=False, max_length=64),
        ),
    ]
