# Generated by Django 3.2 on 2022-05-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_user_jti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jti',
            field=models.CharField(default='5bcebb32fb91bd5458e19f0cda056cb9040b819a3a575cd48d2a9d29e45f65ac', editable=False, max_length=64),
        ),
    ]
