# Generated by Django 3.2 on 2022-05-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_user_jti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jti',
            field=models.CharField(default='0e8c08e9c8504b5c6d9d249d019159278edb81df43ffa47f9ee1cbe415079cea', editable=False, max_length=64),
        ),
    ]
