# Generated by Django 3.2 on 2022-05-12 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_user_jti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jti',
            field=models.CharField(default='147e46364ca531b200fcfe12bb0ed4591e18e352b6c16d7d38054fa7d7f03e21', editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
