# Generated by Django 3.2 on 2022-05-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20220512_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jti',
            field=models.CharField(default='8e1c1929142cd6b58eb5c8bdcccb439c28e114154b91ae446c8a46c51acd6803', editable=False, max_length=64),
        ),
    ]
