# Generated by Django 3.2 on 2022-05-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_alter_user_jti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jti',
            field=models.CharField(default='abfb41dee5052727956ba8ba4969da021eb3c9bb1f1bc6044e17a329cd7e083f', editable=False, max_length=64),
        ),
    ]
