# Generated by Django 3.2 on 2022-05-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_user_jti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jti',
            field=models.CharField(default='0c3873462c3699bb9d8a05fdf34c3f88f11c315cce2ecaad1dde82bdee50e56f', editable=False, max_length=64),
        ),
    ]
