# Generated by Django 3.2 on 2022-05-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_user_jti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jti',
            field=models.CharField(default='b1b91143bafea1d46784b877cf4bcad337a32a5ca52a35f450464112d43943b6', editable=False, max_length=64),
        ),
    ]
