# Generated by Django 3.2 on 2022-05-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_alter_user_jti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jti',
            field=models.CharField(default='6e958f7ceb94339986e3abe4c473f007f25159a050d3e24ddbacba38fc681272', editable=False, max_length=64),
        ),
    ]
