# Generated by Django 3.2 on 2022-05-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_alter_user_jti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jti',
            field=models.CharField(default='e261aa25dcc00cdf565dec58fb6baebc8b828ed8b1974b447dc551ca782e29a0', editable=False, max_length=64),
        ),
    ]
