# Generated by Django 3.2 on 2022-05-23 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0009_remove_coupon_user'),
        ('customers', '0013_alter_user_jti'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coupon.coupon'),
        ),
        migrations.AlterField(
            model_name='user',
            name='jti',
            field=models.CharField(default='6836de4f7725dd8c1959c4c2b6d3560aa40f127002e48988ed11094f51010a53', editable=False, max_length=64),
        ),
    ]
