# Generated by Django 3.2 on 2022-05-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_auto_20220523_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='coupon',
        ),
        migrations.AlterField(
            model_name='user',
            name='jti',
            field=models.CharField(default='81f393782dec301135f8591b17d1dbd15a7ac71f80b61283b96151e3ce8f69ca', editable=False, max_length=64),
        ),
    ]
