# Generated by Django 3.2 on 2022-05-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_auto_20220523_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jti',
            field=models.CharField(default='62b6f40502d65e9c165c76de34d8b431300116e803da606ecded704e4c0b5bfa', editable=False, max_length=64),
        ),
    ]
