# Generated by Django 3.2 on 2022-05-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_cart_applied_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='applied_coupon',
        ),
        migrations.AddField(
            model_name='cart',
            name='no_coupon',
            field=models.BooleanField(default=True),
        ),
    ]
