# Generated by Django 3.2 on 2022-05-20 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20220520_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='no_coupon',
        ),
    ]
